### ISSUE TITLE
Hi! Questions about the capture area

### ISSUE THREAD

**Issue by claudneysessa** [contactlutforrahman/flutter_qr_bar_scanner#1]
Your package is simply fantastic, but I couldn't identify how to limit a capture area, in the case of 2 codes on the same page, capture the first one that the camera identifies, wherever it is. Would it be possible to limit the catch area?

**Comment by contactlutforrahman** [comment]
Change the height and width here.

Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: _camState
          ? Center(
        child: SizedBox(
          height: 1000,
          width: 500,
          child: QRBarScannerCamera(
            onError: (context, error) => Text(
              error.toString(),
              style: TextStyle(color: Colors.red),
            ),
            qrCodeCallback: (code) {
              _qrCallback(code);
            },
          ),
        ),
      )
          : Center(
        child: Text(_qrInfo),
      ),
    );
  }

Like this : 
SizedBox(
          height: 500,
          width: 300,
          child: QRBarScannerCamera(
            onError: (context, error) => Text(
              error.toString(),
              style: TextStyle(color: Colors.red),
            ),
            qrCodeCallback: (code) {
              _qrCallback(code);
            },
          ),

**Comment by claudneysessa** [comment]
I already tried this, but it does not make the limitation on the camera only in the size of the BOX but it keeps getting all the existing codes ...

You would have to limit the area of operation of the camera itself

**Comment by claudneysessa** [comment]
![image](https://user-images.githubusercontent.com/12506432/74300510-bd6b9480-4d2e-11ea-901f-f651ce41224f.png)

**Comment by claudneysessa** [comment]
for example, this image there I want to read the code indicated by the arrow, and it reads the 3 including the two circled

**Comment by claudneysessa** [comment]
![image](https://user-images.githubusercontent.com/12506432/74301480-f35e4800-4d31-11ea-95d3-56856a53d62d.png)
