### ISSUE TITLE
Capture area support?

### ISSUE THREAD

**Issue by bojidartonchev** [contactlutforrahman/flutter_qr_bar_scanner#13]
Hello,

Is there any way i can use the full screen camera, but limit the capture area to a smaller rectangle. This would be very useful when trying to scan a single code out from many.

**Comment by AmG2000** [comment]
Any progress on this?I'm also facing the same issue and have had to revert to a small camera preview area and a black background.

**Comment by contactlutforrahman** [comment]
Full screen camera is a special feature of this plugin. Can you please share your code here?
