### ISSUE TITLE
Support for the new MLKit version

### ISSUE THREAD

**Issue by teolemon** [contactlutforrahman/flutter_qr_bar_scanner#15]
So it seems Google is putting new effort into MLKit. 🎉 
They have revamped the doc, and my understanding is that they released a new version with more features, and no more Firebase requirement 😃 
https://android-developers.googleblog.com/2020/06/mlkit-on-device-machine-learning-solutions.html
https://developers.google.com/ml-kit/vision/barcode-scanning

**Comment by Sadoge** [comment]
I have replaced the GoogleMobileVision API on a forked version of this repository (only for iOS at the moment). You can check if you can use it https://github.com/Sadoge/flutter_qr_bar_scanner

**Comment by AmG2000** [comment]
Great work man. This has solved a lot of my issues

**Comment by pedrovilela** [comment]
I'm having problems to build in iOS release. Anyone else tried to build release for iOS?

![image](https://user-images.githubusercontent.com/1815290/96169109-0b591d80-0ef8-11eb-8b88-ec1bbdc0b7f6.png)

**Comment by contactlutforrahman** [comment]
Right now I've no such plan.
