### ISSUE TITLE
Ability to change / flip camera

### ISSUE THREAD

**Issue by echosalik** [contactlutforrahman/flutter_qr_bar_scanner#17]
Hi
It would be great if the plugin would allow changing camera.
I am forking your repo, I hope I can be of some help.

**Comment by AmG2000** [comment]
Have you been able to work out changing the camera?

**Comment by echosalik** [comment]
Nope. I moved too another library unfortunately.

**Comment by AmG2000** [comment]
Which library?

**Comment by echosalik** [comment]
> 
> 
> Which library?

barcode_scan: 3.0.1

**Comment by contactlutforrahman** [comment]
I will try to add this feature in next version.
