### ISSUE TITLE
QrCameraC1.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by K247Sagar** [contactlutforrahman/flutter_qr_bar_scanner#24]
Hi @contactlutforrahman can you please look into below issue : 

Logs :

Note: /home/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_qr_bar_scanner-1.0.2/android/src/main/java/com/github/contactlutforrahman/flutter_qr_bar_scanner/QrCameraC1.java uses or overrides a deprecated API.

**Comment by contactlutforrahman** [comment]
Released new version just now with Null safety and compatible with Flutter version 2.2. If you want you can try it.
