### ISSUE TITLE
Low resolution cameras

### ISSUE THREAD

**Issue by AmG2000** [contactlutforrahman/flutter_qr_bar_scanner#28]
I've been writing an app that scans barcodes, and realized the results aren't reliable when scanning on devices with really low camera resolution (sub 8mp).  Any suggestions on what I can do to increase the scanning reliability on such devices?

**Comment by contactlutforrahman** [comment]
Released new version just now with Null safety and compatible with Flutter version 2.2. If you want you can try it.
