### ISSUE TITLE
Widget w/ AnimatedOpacity- always running

### ISSUE THREAD

**Issue by nholmvio** [contactlutforrahman/flutter_qr_bar_scanner#29]
Hi all...i'm hoping for some advice.  I'm attempting to use this widget within an AnimatedOpacity (that triggers when it was intended to be scanning...) and that is initially not visible (and i thought would be not active).   However, it is still reading QR codes "behind the scenes" triggering the callback even when widget is not visible, nor should be scanning. 

Is there a better way to be triggering this (i can stop the reader in a postFrameCallback after the initial build, but don't successfully get it restarted. 

any advice or recommendations from others on how to better handle this usage that may be started and stopped?

**Comment by contactlutforrahman** [comment]
Released new version just now with Null safety and compatible with Flutter version 2.2. If you want you can try it.
