### ISSUE TITLE
Outdated dependency for Flutter 2.+

### ISSUE THREAD

**Issue by mazzadomenico** [contactlutforrahman/flutter_qr_bar_scanner#30]
Hi,
latest version of flutter_qr_bar_scanner (1.0.2) depends on al old version of native_device_orientation (0.3.0) wich cause issues on build with Flutter 2.+.

Thanks a lot

**Comment by agadev** [comment]
See PR 32 [https://github.com/contactlutforrahman/flutter_qr_bar_scanner/pull/32](url)

**Comment by contactlutforrahman** [comment]
Released new version just now with Null safety and compatible with Flutter version 2.2. If you want you can try it.
