### ISSUE TITLE
Support Android v2 embedding

### ISSUE THREAD

**Issue by nilotpalkapri** [contactlutforrahman/flutter_qr_bar_scanner#35]
Please consider upgrading the package

**Comment by contactlutforrahman** [comment]
What kinds of issue are you having? I've tested just now with flutter's latest version and I found no error.

**Comment by nilotpalkapri** [comment]
![image](https://user-images.githubusercontent.com/65615877/131235294-76203869-900e-4205-afa3-90fa9ee810b4.png)

/home/nilotpalkapri/snap/flutter/common/flutter/bin/flutter --no-color pub get
Waiting for another flutter command to release the startup lock...
Running "flutter pub get" in doc_scan...                           10.9s
The plugins `flutter_qr_bar_scanner, image_editor` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Process finished with exit code 0


**I am in beta latest.

**Comment by contactlutforrahman** [comment]
Please create a new project with flutter stable version 2.2.3 and use only this plugin and try it.

**Comment by nilotpalkapri** [comment]
In stable channel there will not be any issue, it is good if you consider migrating otherwise no issue as of now, this is just a warning, in future it may create problem.

**Comment by contactlutforrahman** [comment]
okay.
