### ISSUE TITLE
Android V2 Embedding

### ISSUE THREAD

**Issue by WasimNaryabi** [contactlutforrahman/flutter_qr_bar_scanner#37]
The plugin `flutter_qr_bar_scanner` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are a plugin author, take a look at the docs for migrating the plugin to the V2 embedding.

**Comment by contactlutforrahman** [comment]
The issue is solved in latest version
