### ISSUE TITLE
podspec syntax error

### ISSUE THREAD

**Issue by LamimPaulo** [contactlutforrahman/flutter_qr_bar_scanner#5]
Got this syntax error while pod install on mac

it was needed to edit the file to proceed with the pod install

![aa](https://user-images.githubusercontent.com/49486299/76352384-ba43d400-62ed-11ea-9c0f-01bde6fff5e1.jpeg)

**Comment by DuQuanzhong** [comment]
the same problem

**Comment by pvarry** [comment]
A Pull Request is open for this problem : https://github.com/contactlutforrahman/flutter_qr_bar_scanner/pull/6
