### ISSUE TITLE
Some features in iOS are not implemented

### ISSUE THREAD

**Issue by qwertyuiop17u** [contactlutforrahman/flutter_qr_bar_scanner#7]
Compare the source code of Android and iOS, there are some features still not finished for iOS, such as adding restriction for BarcodeFormats.

**Comment by ulusoyca** [comment]
I think this should be opened. While the barcode format restriction works on Android, it doesn't work on iOS. Any idea why is this closed? Shall we open a separate ticket for barcode restriction?
