### ISSUE TITLE
MissingPluginException - IOS

### ISSUE THREAD

**Issue by muhammadmateen027** [contactlutforrahman/flutter_qr_bar_scanner#8]
[!] Failed to load 'flutter_qr_bar_scanner' podspec: 
[!] Invalid `flutter_qr_bar_scanner.podspec` file: syntax error, unexpected tIDENTIFIER, expecting end
...g QR & Bar codes using Google's Mobile Vision API'

**Comment by kaiquecruz** [comment]
I forked this project and edited the file: flutter_qr_bar_scanner.podspec
Removing invalid character, **'**, from Google**'**s

**Comment by LamimPaulo** [comment]
> I forked this project and edited the file: flutter_qr_bar_scanner.podspec
> Removing the invalid character, ', from Google's.
> Until they update the project.

Kaique, any problems building to iOs release ? mobile visions seems to be outdated

im getting this-
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by kaiquecruz** [comment]
> > I forked this project and edited the file: flutter_qr_bar_scanner.podspec
> > Removing the invalid character, ', from Google's.
> > Until they update the project.
> 
> Kaique, any problems building to iOs release ? mobile visions seems to be outdated
> 
> im getting this-
> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

I used another plugin: r_scan
